window.TRIP_DATA = {
  "source": {
    "title": "Japan 2026 Travel Database v1",
    "spreadsheetId": "10Zxakb-YtuX3SJqmPNMzMNPUIvprJuriqj9NZyAYKLM",
    "url": "https://docs.google.com/spreadsheets/d/10Zxakb-YtuX3SJqmPNMzMNPUIvprJuriqj9NZyAYKLM/edit",
    "syncedAt": "2026-09-07T00:00:00+09:00",
    "mode": "build_snapshot"
  },
  "trip": {
    "id": "TRIP001",
    "name": "Japan 2026 | Osaka – Kyoto – Nara – Tokyo",
    "startDate": "2026-10-09",
    "endDate": "2026-10-18",
    "travelers": 2,
    "jpyToThb": 0.23
  },
  "itinerary": [
    {
      "Itinerary_ID": "ITI001",
      "Trip_ID": "TRIP001",
      "Date": "10/9/2026",
      "Day": "ศุกร์",
      "City": "Osaka",
      "Period": "เช้ามืด",
      "Start_Time": "03:55",
      "End_Time": "11:50",
      "Start_DateTime_ISO": "2026-10-09T03:55:00+09:00",
      "End_DateTime_ISO": "2026-10-09T11:50:00+09:00",
      "Activity": "บินจากกรุงเทพฯ ไปโอซาก้า",
      "Place_ID": "PLACE029",
      "Place_Name": "DMK T1 → KIX T1",
      "Status": "Confirmed",
      "Booking_ID": "BOOK001",
      "Notes": "Booking ref •••• PPTR"
    },
    {
      "Itinerary_ID": "ITI002",
      "Trip_ID": "TRIP001",
      "Date": "10/9/2026",
      "Day": "ศุกร์",
      "City": "Osaka",
      "Period": "บ่าย",
      "Start_Time": "12:00",
      "End_Time": "15:00",
      "Start_DateTime_ISO": "2026-10-09T12:00:00+09:00",
      "End_DateTime_ISO": "2026-10-09T15:00:00+09:00",
      "Activity": "ตรวจคนเข้าเมือง รับกระเป๋า และเดินทางเข้าเมือง",
      "Place_ID": "HOTEL001",
      "Place_Name": "KIX → Shinfukae",
      "Transport_ID": "TRANS001",
      "Status": "Suggested",
      "Notes": "เผื่อเวลาสำหรับกระเป๋าใหญ่ 3 ใบ"
    },
    {
      "Itinerary_ID": "ITI003",
      "Trip_ID": "TRIP001",
      "Date": "10/9/2026",
      "Day": "ศุกร์",
      "City": "Osaka",
      "Period": "เย็น",
      "Start_Time": "15:00",
      "End_Time": "21:00",
      "Start_DateTime_ISO": "2026-10-09T15:00:00+09:00",
      "End_DateTime_ISO": "2026-10-09T21:00:00+09:00",
      "Activity": "เช็กอิน พัก และเดินเล่น Namba / Dotonbori",
      "Place_ID": "PLACE026",
      "Place_Name": "Shinfukae → Namba",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "เช็กอินได้ 14:00–24:00"
    },
    {
      "Itinerary_ID": "ITI004",
      "Trip_ID": "TRIP001",
      "Date": "10/10/2026",
      "Day": "เสาร์",
      "City": "Osaka",
      "Period": "เช้า",
      "Start_Time": "09:00",
      "End_Time": "12:00",
      "Start_DateTime_ISO": "2026-10-10T09:00:00+09:00",
      "End_DateTime_ISO": "2026-10-10T12:00:00+09:00",
      "Activity": "เที่ยว Osaka Castle Museum และสวนปราสาท",
      "Place_ID": "PLACE001",
      "Place_Name": "Osaka Castle",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "พิพิธภัณฑ์ประกาศเปิด 09:00–17:30 ในช่วงนี้",
      "Link": "https://www.osakacastle.net/english/"
    },
    {
      "Itinerary_ID": "ITI005",
      "Trip_ID": "TRIP001",
      "Date": "10/10/2026",
      "Day": "เสาร์",
      "City": "Osaka",
      "Period": "บ่าย",
      "Start_Time": "14:00",
      "End_Time": "18:00",
      "Start_DateTime_ISO": "2026-10-10T14:00:00+09:00",
      "End_DateTime_ISO": "2026-10-10T18:00:00+09:00",
      "Activity": "เที่ยว Osaka Aquarium Kaiyukan",
      "Place_ID": "PLACE002",
      "Place_Name": "Tempozan",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "เวลาเปิดเปลี่ยนตามฤดูกาล ต้องตรวจปฏิทินก่อนวันไป",
      "Link": "https://www.kaiyukan.com/language/eng/information.html"
    },
    {
      "Itinerary_ID": "ITI006",
      "Trip_ID": "TRIP001",
      "Date": "10/10/2026",
      "Day": "เสาร์",
      "City": "Osaka",
      "Period": "เย็น",
      "Start_Time": "18:00",
      "End_Time": "21:00",
      "Start_DateTime_ISO": "2026-10-10T18:00:00+09:00",
      "End_DateTime_ISO": "2026-10-10T21:00:00+09:00",
      "Activity": "Tempozan / กลับ Namba รับประทานอาหาร",
      "Place_ID": "PLACE026",
      "Place_Name": "Osaka",
      "Transport_ID": "TRANS006",
      "Status": "Optional",
      "Notes": "ปรับตามแรงและเวลาปิด"
    },
    {
      "Itinerary_ID": "ITI007",
      "Trip_ID": "TRIP001",
      "Date": "10/11/2026",
      "Day": "อาทิตย์",
      "City": "Kyoto",
      "Period": "เช้า",
      "Start_Time": "07:00",
      "End_Time": "11:00",
      "Start_DateTime_ISO": "2026-10-11T07:00:00+09:00",
      "End_DateTime_ISO": "2026-10-11T11:00:00+09:00",
      "Activity": "เดินทางไป Kyoto และเที่ยว Kiyomizu-dera",
      "Place_ID": "PLACE003",
      "Place_Name": "Higashiyama",
      "Transport_ID": "TRANS003",
      "Status": "Suggested",
      "Notes": "ไปเช้าเพื่อลดความหนาแน่น",
      "Link": "https://www.kiyomizudera.or.jp/en/visit/"
    },
    {
      "Itinerary_ID": "ITI008",
      "Trip_ID": "TRIP001",
      "Date": "10/11/2026",
      "Day": "อาทิตย์",
      "City": "Kyoto",
      "Period": "บ่าย",
      "Start_Time": "11:00",
      "End_Time": "16:30",
      "Start_DateTime_ISO": "2026-10-11T11:00:00+09:00",
      "End_DateTime_ISO": "2026-10-11T16:30:00+09:00",
      "Activity": "Sannenzaka – Ninenzaka – Yasaka Shrine – Gion",
      "Place_ID": "PLACE004",
      "Place_Name": "Higashiyama / Gion",
      "Status": "Suggested",
      "Notes": "เส้นทางต่อเนื่อง เดินค่อนข้างมาก"
    },
    {
      "Itinerary_ID": "ITI009",
      "Trip_ID": "TRIP001",
      "Date": "10/11/2026",
      "Day": "อาทิตย์",
      "City": "Osaka",
      "Period": "เย็น",
      "Start_Time": "17:00",
      "End_Time": "20:00",
      "Start_DateTime_ISO": "2026-10-11T17:00:00+09:00",
      "End_DateTime_ISO": "2026-10-11T20:00:00+09:00",
      "Activity": "กลับ Osaka และพัก",
      "Place_ID": "HOTEL001",
      "Place_Name": "Kyoto → Shinfukae",
      "Status": "Suggested",
      "Notes": "เตรียมวัน Nara"
    },
    {
      "Itinerary_ID": "ITI010",
      "Trip_ID": "TRIP001",
      "Date": "10/12/2026",
      "Day": "จันทร์",
      "City": "Nara",
      "Period": "เช้า",
      "Start_Time": "08:00",
      "End_Time": "12:00",
      "Start_DateTime_ISO": "2026-10-12T08:00:00+09:00",
      "End_DateTime_ISO": "2026-10-12T12:00:00+09:00",
      "Activity": "Nara Park และ Todai-ji",
      "Place_ID": "PLACE007",
      "Place_Name": "Nara",
      "Transport_ID": "TRANS004",
      "Status": "Suggested",
      "Notes": "เผื่อเวลาเดินในสวน"
    },
    {
      "Itinerary_ID": "ITI011",
      "Trip_ID": "TRIP001",
      "Date": "10/12/2026",
      "Day": "จันทร์",
      "City": "Nara",
      "Period": "บ่าย",
      "Start_Time": "12:00",
      "End_Time": "16:00",
      "Start_DateTime_ISO": "2026-10-12T12:00:00+09:00",
      "End_DateTime_ISO": "2026-10-12T16:00:00+09:00",
      "Activity": "Kasuga Taisha / ย่าน Mochiidono",
      "Place_ID": "PLACE007",
      "Place_Name": "Nara",
      "Status": "Optional",
      "Notes": "ตัดออกได้หากเหนื่อย"
    },
    {
      "Itinerary_ID": "ITI012",
      "Trip_ID": "TRIP001",
      "Date": "10/12/2026",
      "Day": "จันทร์",
      "City": "Osaka",
      "Period": "เย็น",
      "Start_Time": "17:30",
      "End_Time": "21:00",
      "Start_DateTime_ISO": "2026-10-12T17:30:00+09:00",
      "End_DateTime_ISO": "2026-10-12T21:00:00+09:00",
      "Activity": "กลับโรงแรม จัดกระเป๋า และเตรียม USJ",
      "Place_ID": "HOTEL001",
      "Place_Name": "Shinfukae",
      "Status": "Must do",
      "Booking_ID": "BOOK003",
      "Notes": "แยกของจำเป็นสำหรับคืนบนรถบัส"
    },
    {
      "Itinerary_ID": "ITI013",
      "Trip_ID": "TRIP001",
      "Date": "10/13/2026",
      "Day": "อังคาร",
      "City": "Osaka",
      "Period": "เช้า",
      "Start_Time": "ก่อนเปิด",
      "End_Time": "12:00",
      "End_DateTime_ISO": "2026-10-13T12:00:00+09:00",
      "Activity": "เช็กเอาต์ ฝาก/จัดการสัมภาระ และเข้า USJ",
      "Place_ID": "PLACE011",
      "Place_Name": "Universal Studios Japan",
      "Transport_ID": "TRANS006",
      "Status": "Needs confirmation",
      "Booking_ID": "BOOK003",
      "Notes": "ต้องวางแผนกระเป๋า 3 ใบก่อนวันจริง",
      "Link": "https://www.usj.co.jp/web/en/us/park-guide/schedule/park-hour"
    },
    {
      "Itinerary_ID": "ITI014",
      "Trip_ID": "TRIP001",
      "Date": "10/13/2026",
      "Day": "อังคาร",
      "City": "Osaka",
      "Period": "ทั้งวัน",
      "Start_Time": "เปิดสวน",
      "End_Time": "20:30",
      "End_DateTime_ISO": "2026-10-13T20:30:00+09:00",
      "Activity": "เที่ยว USJ / SUPER NINTENDO WORLD™ / Halloween events",
      "Place_ID": "PLACE011",
      "Place_Name": "USJ",
      "Status": "Needs booking",
      "Booking_ID": "BOOK003",
      "Notes": "ตั๋วและ Express Pass ยังไม่แสดงว่ายืนยันแล้ว",
      "Link": "https://www.usj.co.jp/web/en/us/park-guide/schedule/park-hour"
    },
    {
      "Itinerary_ID": "ITI015",
      "Trip_ID": "TRIP001",
      "Date": "10/13/2026",
      "Day": "อังคาร",
      "City": "Night Bus",
      "Period": "กลางคืน",
      "Start_Time": "21:55",
      "End_Time": "06:36+1",
      "Start_DateTime_ISO": "2026-10-13T21:55:00+09:00",
      "End_DateTime_ISO": "2026-10-14T06:36:00+09:00",
      "Activity": "Orion 6112 จาก USJ ไป Tokyo Station Yaesu",
      "Place_ID": "PLACE012",
      "Place_Name": "USJ → Tokyo",
      "Transport_ID": "TRANS005",
      "Status": "Needs booking",
      "Budget_JPY": "8000",
      "Booking_ID": "BOOK003",
      "Notes": "¥4,000/คน; ต้องยืนยันกระเป๋าใบที่ 3"
    },
    {
      "Itinerary_ID": "ITI016",
      "Trip_ID": "TRIP001",
      "Date": "10/14/2026",
      "Day": "พุธ",
      "City": "Tokyo",
      "Period": "เช้า",
      "Start_Time": "06:36",
      "End_Time": "09:00",
      "Start_DateTime_ISO": "2026-10-14T06:36:00+09:00",
      "End_DateTime_ISO": "2026-10-14T09:00:00+09:00",
      "Activity": "ถึง Tokyo Station และนำกระเป๋าไปฝาก",
      "Place_ID": "PLACE012",
      "Place_Name": "Yaesu / Big Echo Yaesu",
      "Status": "Needs booking",
      "Budget_JPY": "2400",
      "Booking_ID": "BOOK007",
      "Notes": "3 ใบ × ¥800; ฝากประมาณ 08:30–09:00"
    },
    {
      "Itinerary_ID": "ITI017",
      "Trip_ID": "TRIP001",
      "Date": "10/14/2026",
      "Day": "พุธ",
      "City": "Tokyo",
      "Period": "สาย–บ่าย",
      "Start_Time": "09:00",
      "End_Time": "15:00",
      "Start_DateTime_ISO": "2026-10-14T09:00:00+09:00",
      "End_DateTime_ISO": "2026-10-14T15:00:00+09:00",
      "Activity": "เที่ยวเบา ๆ บริเวณ Tokyo Station / Marunouchi",
      "Place_ID": "PLACE012",
      "Place_Name": "Tokyo Station",
      "Status": "Suggested",
      "Notes": "หลีกเลี่ยงเส้นทางไกลหลังเดินทางกลางคืน"
    },
    {
      "Itinerary_ID": "ITI018",
      "Trip_ID": "TRIP001",
      "Date": "10/14/2026",
      "Day": "พุธ",
      "City": "Tokyo",
      "Period": "บ่าย",
      "Start_Time": "15:00",
      "End_Time": "17:00",
      "Start_DateTime_ISO": "2026-10-14T15:00:00+09:00",
      "End_DateTime_ISO": "2026-10-14T17:00:00+09:00",
      "Activity": "รับกระเป๋าและไปเช็กอิน Noble Park KINSHICHO 201",
      "Place_ID": "HOTEL002",
      "Place_Name": "Tokyo Station → Kinshicho",
      "Transport_ID": "TRANS006",
      "Status": "Confirmed",
      "Booking_ID": "BOOK008",
      "Notes": "ที่พักไม่รับฝากกระเป๋า; early check-in 12:00 ¥4,500 หากว่าง"
    },
    {
      "Itinerary_ID": "ITI019",
      "Trip_ID": "TRIP001",
      "Date": "10/14/2026",
      "Day": "พุธ",
      "City": "Tokyo",
      "Period": "เย็น",
      "Start_Time": "18:00",
      "End_Time": "21:00",
      "Start_DateTime_ISO": "2026-10-14T18:00:00+09:00",
      "End_DateTime_ISO": "2026-10-14T21:00:00+09:00",
      "Activity": "Oshiage / Tokyo Skytree Town",
      "Place_ID": "PLACE014",
      "Place_Name": "Oshiage",
      "Transport_ID": "TRANS006",
      "Status": "Optional",
      "Notes": "Kinshicho ไป Oshiage 1 สถานี"
    },
    {
      "Itinerary_ID": "ITI020",
      "Trip_ID": "TRIP001",
      "Date": "10/15/2026",
      "Day": "พฤหัส",
      "City": "Tokyo",
      "Period": "เช้า",
      "Start_Time": "08:00",
      "End_Time": "12:00",
      "Start_DateTime_ISO": "2026-10-15T08:00:00+09:00",
      "End_DateTime_ISO": "2026-10-15T12:00:00+09:00",
      "Activity": "Asakusa และ Senso-ji",
      "Place_ID": "PLACE015",
      "Place_Name": "Asakusa",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "เริ่มเช้าแล้วต่อย่านใกล้กัน"
    },
    {
      "Itinerary_ID": "ITI021",
      "Trip_ID": "TRIP001",
      "Date": "10/15/2026",
      "Day": "พฤหัส",
      "City": "Tokyo",
      "Period": "บ่าย",
      "Start_Time": "13:00",
      "End_Time": "17:00",
      "Start_DateTime_ISO": "2026-10-15T13:00:00+09:00",
      "End_DateTime_ISO": "2026-10-15T17:00:00+09:00",
      "Activity": "Ueno / Ameyoko",
      "Place_ID": "PLACE016",
      "Place_Name": "Ueno",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "พักรับประทานอาหารระหว่างทาง"
    },
    {
      "Itinerary_ID": "ITI022",
      "Trip_ID": "TRIP001",
      "Date": "10/15/2026",
      "Day": "พฤหัส",
      "City": "Tokyo",
      "Period": "เย็น",
      "Start_Time": "17:30",
      "End_Time": "21:00",
      "Start_DateTime_ISO": "2026-10-15T17:30:00+09:00",
      "End_DateTime_ISO": "2026-10-15T21:00:00+09:00",
      "Activity": "Akihabara",
      "Place_ID": "PLACE018",
      "Place_Name": "Akihabara",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "Kinshicho → Akihabara ประมาณ 8 นาทีโดย JR"
    },
    {
      "Itinerary_ID": "ITI023",
      "Trip_ID": "TRIP001",
      "Date": "10/16/2026",
      "Day": "ศุกร์",
      "City": "Tokyo",
      "Period": "เช้า",
      "Start_Time": "09:00",
      "End_Time": "13:00",
      "Start_DateTime_ISO": "2026-10-16T09:00:00+09:00",
      "End_DateTime_ISO": "2026-10-16T13:00:00+09:00",
      "Activity": "Meiji Jingu และ Harajuku",
      "Place_ID": "PLACE020",
      "Place_Name": "Harajuku",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "จัดเส้นทางฝั่งตะวันตกในวันเดียว"
    },
    {
      "Itinerary_ID": "ITI024",
      "Trip_ID": "TRIP001",
      "Date": "10/16/2026",
      "Day": "ศุกร์",
      "City": "Tokyo",
      "Period": "บ่าย",
      "Start_Time": "13:00",
      "End_Time": "18:00",
      "Start_DateTime_ISO": "2026-10-16T13:00:00+09:00",
      "End_DateTime_ISO": "2026-10-16T18:00:00+09:00",
      "Activity": "Shibuya",
      "Place_ID": "PLACE021",
      "Place_Name": "Shibuya",
      "Transport_ID": "TRANS006",
      "Status": "Suggested",
      "Notes": "จาก Kinshicho นั่ง Hanzomon Line ได้"
    },
    {
      "Itinerary_ID": "ITI025",
      "Trip_ID": "TRIP001",
      "Date": "10/16/2026",
      "Day": "ศุกร์",
      "City": "Tokyo",
      "Period": "เย็น",
      "Start_Time": "18:00",
      "End_Time": "21:30",
      "Start_DateTime_ISO": "2026-10-16T18:00:00+09:00",
      "End_DateTime_ISO": "2026-10-16T21:30:00+09:00",
      "Activity": "Shinjuku",
      "Place_ID": "PLACE022",
      "Place_Name": "Shinjuku",
      "Transport_ID": "TRANS006",
      "Status": "Optional",
      "Notes": "กลับ Kinshicho โดยเผื่อเวลาเปลี่ยนสาย"
    },
    {
      "Itinerary_ID": "ITI026",
      "Trip_ID": "TRIP001",
      "Date": "10/17/2026",
      "Day": "เสาร์",
      "City": "Tokyo",
      "Period": "เช้า–บ่าย",
      "Start_Time": "09:00",
      "End_Time": "16:00",
      "Start_DateTime_ISO": "2026-10-17T09:00:00+09:00",
      "End_DateTime_ISO": "2026-10-17T16:00:00+09:00",
      "Activity": "Nakano Broadway / Ikebukuro สำหรับช้อปปิ้ง",
      "Place_ID": "PLACE023",
      "Place_Name": "Nakano / Ikebukuro",
      "Transport_ID": "TRANS006",
      "Status": "Optional",
      "Notes": "เลือกย่านหลักตามร้านที่ต้องการ"
    },
    {
      "Itinerary_ID": "ITI027",
      "Trip_ID": "TRIP001",
      "Date": "10/17/2026",
      "Day": "เสาร์",
      "City": "Tokyo",
      "Period": "เย็น",
      "Start_Time": "16:00",
      "End_Time": "21:00",
      "Start_DateTime_ISO": "2026-10-17T16:00:00+09:00",
      "End_DateTime_ISO": "2026-10-17T21:00:00+09:00",
      "Activity": "ซื้อของฝากและจัดกระเป๋า",
      "Place_ID": "HOTEL002",
      "Place_Name": "Tokyo / Kinshicho",
      "Transport_ID": "TRANS006",
      "Status": "Must do",
      "Booking_ID": "BOOK007",
      "Notes": "ตรวจน้ำหนักสัมภาระและของเหลว"
    },
    {
      "Itinerary_ID": "ITI028",
      "Trip_ID": "TRIP001",
      "Date": "10/18/2026",
      "Day": "อาทิตย์",
      "City": "Tokyo",
      "Period": "เช้า",
      "Start_Time": "ตามที่พัก",
      "End_Time": "11:00",
      "End_DateTime_ISO": "2026-10-18T11:00:00+09:00",
      "Activity": "เช็กเอาต์และเดินทางไป Narita",
      "Place_ID": "PLACE025",
      "Place_Name": "Kinshicho → NRT",
      "Transport_ID": "TRANS007",
      "Status": "Needs confirmation",
      "Notes": "ที่พักไม่รับฝากกระเป๋าหลังเช็กเอาต์"
    },
    {
      "Itinerary_ID": "ITI029",
      "Trip_ID": "TRIP001",
      "Date": "10/18/2026",
      "Day": "อาทิตย์",
      "City": "Tokyo",
      "Period": "บ่าย",
      "Start_Time": "14:00",
      "End_Time": "17:00",
      "Start_DateTime_ISO": "2026-10-18T14:00:00+09:00",
      "End_DateTime_ISO": "2026-10-18T17:00:00+09:00",
      "Activity": "เช็กอินเที่ยวบินและผ่าน ตม.",
      "Place_ID": "PLACE025",
      "Place_Name": "Narita Airport",
      "Status": "Confirmed",
      "Notes": "ควรถึงสนามบินล่วงหน้าอย่างน้อยประมาณ 3 ชม."
    },
    {
      "Itinerary_ID": "ITI030",
      "Trip_ID": "TRIP001",
      "Date": "10/18/2026",
      "Day": "อาทิตย์",
      "City": "เดินทาง",
      "Period": "เย็น",
      "Start_Time": "17:00",
      "End_Time": "21:40",
      "Start_DateTime_ISO": "2026-10-18T17:00:00+09:00",
      "End_DateTime_ISO": "2026-10-18T21:40:00+09:00",
      "Activity": "บินกลับกรุงเทพฯ",
      "Place_Name": "NRT → Bangkok",
      "Status": "Confirmed",
      "Booking_ID": "BOOK010",
      "Notes": "Booking ref •••• UPQ9"
    }
  ],
  "hotels": [
    {
      "Hotel_ID": "HOTEL001",
      "Trip_ID": "TRIP001",
      "Hotel_Name": "Tanimachikun Star Hotel Shinfukae 59",
      "City": "Osaka",
      "Check_in_Date": "10/9/2026",
      "Check_out_Date": "10/13/2026",
      "Check_in_Time": "14:00",
      "Check_out_Time": "12:00",
      "Booking_ID": "BOOK002",
      "Provider": "Trip.com",
      "Price_THB": "6869.26",
      "Address": "4-3-10 Kamiji, Higashinari Ward, Osaka 537-0003, Japan",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Tanimachikun%20Star%20Hotel%20Shinfukae%2059",
      "Self_Check_in": "TRUE",
      "Status": "Paid",
      "Notes": "4 nights; 2 people; contact property in advance with ID, arrival time and flight details",
      "Booking_No_Masked": "•••• 4899"
    },
    {
      "Hotel_ID": "HOTEL002",
      "Trip_ID": "TRIP001",
      "Hotel_Name": "Noble Park KINSHICHO 201",
      "City": "Tokyo",
      "Check_in_Date": "10/14/2026",
      "Check_out_Date": "10/18/2026",
      "Check_in_Time": "16:00",
      "Check_out_Time": "11:00",
      "Booking_ID": "BOOK008",
      "Provider": "Trip.com",
      "Price_THB": "10924.98",
      "Address": "Kinshicho area, Sumida City, Tokyo",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Noble%20Park%20KINSHICHO%20201",
      "Self_Check_in": "TRUE",
      "Status": "Paid",
      "Notes": "No luggage storage before/after stay; early check-in from 12:00 may be available for ¥4,500; verify exact address and final paid amount"
    }
  ],
  "flights": [
    {
      "Flight_ID": "FLIGHT001",
      "Trip_ID": "TRIP001",
      "Direction": "Outbound",
      "Date": "10/9/2026",
      "Departure_Time": "03:55",
      "Arrival_Time": "11:50",
      "Origin_Airport": "DMK",
      "Origin_Terminal": "T1",
      "Destination_Airport": "KIX",
      "Destination_Terminal": "T1",
      "Booking_ID": "BOOK001",
      "Check_in_Notes": "Verify airline, flight number and baggage allowance; online check-in",
      "Status": "Confirmed",
      "Booking_Ref_Masked": "•••• 7797"
    },
    {
      "Flight_ID": "FLIGHT002",
      "Trip_ID": "TRIP001",
      "Direction": "Inbound",
      "Date": "10/18/2026",
      "Departure_Time": "17:00",
      "Arrival_Time": "21:40",
      "Origin_Airport": "NRT",
      "Destination_Airport": "Bangkok",
      "Booking_ID": "BOOK010",
      "Check_in_Notes": "Arrive at airport around 3 hours early; verify terminal and baggage allowance",
      "Status": "Confirmed",
      "Booking_Ref_Masked": "•••• 7797"
    }
  ],
  "transport": [
    {
      "Transport_ID": "TRANS001",
      "Trip_ID": "TRIP001",
      "Type": "Airport transfer",
      "Route": "KIX → Shinfukae",
      "Date": "10/9/2026",
      "Departure_Time": "12:00",
      "Arrival_Time": "15:00",
      "Operator": "Railway",
      "Baggage_Rule": "3 large bags",
      "Status": "Suggested",
      "Notes": "Choose route after immigration"
    },
    {
      "Transport_ID": "TRANS002",
      "Trip_ID": "TRIP001",
      "Type": "Metro",
      "Route": "Osaka local travel",
      "Operator": "Osaka Metro",
      "Status": "Planned",
      "Notes": "Namba, Dotonbori, Osaka Castle and Tempozan"
    },
    {
      "Transport_ID": "TRANS003",
      "Trip_ID": "TRIP001",
      "Type": "Day trip",
      "Route": "Osaka ↔ Kyoto",
      "Date": "10/11/2026",
      "Departure_Time": "07:00",
      "Arrival_Time": "20:00",
      "Operator": "Railway",
      "Status": "Planned",
      "Notes": "Kiyomizu-dera, Gion"
    },
    {
      "Transport_ID": "TRANS004",
      "Trip_ID": "TRIP001",
      "Type": "Day trip",
      "Route": "Osaka ↔ Nara",
      "Date": "10/12/2026",
      "Departure_Time": "08:00",
      "Arrival_Time": "21:00",
      "Operator": "Kintetsu / JR",
      "Status": "Planned",
      "Notes": "Nara Park and Todai-ji"
    },
    {
      "Transport_ID": "TRANS005",
      "Trip_ID": "TRIP001",
      "Type": "Night Bus",
      "Route": "USJ → Tokyo Station Yaesu",
      "Date": "10/13/2026",
      "Departure_Time": "21:55",
      "Arrival_Time": "06:36+1",
      "Operator": "Orion Bus",
      "Service_No": "6112",
      "Price_JPY": "8000",
      "Price_THB": "1840",
      "Booking_ID": "BOOK006",
      "Baggage_Rule": "1 large bag/person guaranteed; third bag requires written confirmation",
      "Status": "Needs booking",
      "Notes": "¥4,000/person; 2 passengers"
    },
    {
      "Transport_ID": "TRANS006",
      "Trip_ID": "TRIP001",
      "Type": "Rail / Metro",
      "Route": "Tokyo local travel",
      "Date": "10/14/2026",
      "Operator": "JR / Tokyo Metro",
      "Status": "Planned",
      "Notes": "Kinshicho base"
    },
    {
      "Transport_ID": "TRANS007",
      "Trip_ID": "TRIP001",
      "Type": "Airport transfer",
      "Route": "Kinshicho → NRT",
      "Date": "10/18/2026",
      "Arrival_Time": "14:00",
      "Status": "Needs confirmation",
      "Notes": "Choose route suitable for 3 large bags"
    }
  ],
  "luggage": [
    {
      "Luggage_ID": "LUG001",
      "Trip_ID": "TRIP001",
      "Place_Name": "Big Echo Yaesu Main Store",
      "City": "Tokyo",
      "Area": "Yaesu",
      "Date": "10/14/2026",
      "Open_Time": "00:00",
      "Close_Time": "24:00",
      "Bag_Count": "3",
      "Price_Per_Bag_JPY": "800",
      "Total_JPY": "2400",
      "Max_Size": "Verify 29–30 inch",
      "Booking_Required": "TRUE",
      "Address": "Near Tokyo Station Yaesu exit",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Big%20Echo%20Yaesu%20Main%20Store",
      "Status": "Preferred",
      "Notes": "Deposit ~08:30–09:00; collect ~15:00–15:30; ecbo cloak"
    },
    {
      "Luggage_ID": "LUG002",
      "Trip_ID": "TRIP001",
      "Place_Name": "Tokyo VIP Lounge",
      "City": "Tokyo",
      "Area": "Nihombashi / Yaesu",
      "Date": "10/14/2026",
      "Open_Time": "08:00",
      "Close_Time": "23:30",
      "Bag_Count": "3",
      "Price_Per_Bag_JPY": "750",
      "Total_JPY": "2250",
      "Max_Size": "Verify 29–30 inch",
      "Booking_Required": "TRUE",
      "Address": "About 6 minutes from Tokyo Station",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Tokyo%20VIP%20Lounge",
      "Status": "Alternative",
      "Notes": "Cheaper option via Bounce; verify live availability"
    }
  ],
  "places": [
    {
      "Place_ID": "PLACE001",
      "Place_Name": "Osaka Castle",
      "Category": "Sightseeing",
      "City": "Osaka",
      "Area": "Osaka Castle",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Osaka%20Castle",
      "Official_URL": "https://www.osakacastle.net/english/",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE002",
      "Place_Name": "Osaka Aquarium Kaiyukan",
      "Category": "Sightseeing",
      "City": "Osaka",
      "Area": "Tempozan",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Osaka%20Aquarium%20Kaiyukan",
      "Official_URL": "https://www.kaiyukan.com/language/eng/information.html",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE003",
      "Place_Name": "Kiyomizu-dera",
      "Category": "Sightseeing",
      "City": "Kyoto",
      "Area": "Higashiyama",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Kiyomizu-dera",
      "Official_URL": "https://www.kiyomizudera.or.jp/en/visit/",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE004",
      "Place_Name": "Sannenzaka & Ninenzaka",
      "Category": "Sightseeing",
      "City": "Kyoto",
      "Area": "Higashiyama",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Sannenzaka%20Ninenzaka",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE005",
      "Place_Name": "Yasaka Shrine",
      "Category": "Sightseeing",
      "City": "Kyoto",
      "Area": "Gion",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Yasaka%20Shrine",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE006",
      "Place_Name": "Gion",
      "Category": "Area",
      "City": "Kyoto",
      "Area": "Gion",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Gion%20Kyoto",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE007",
      "Place_Name": "Nara Park",
      "Category": "Sightseeing",
      "City": "Nara",
      "Area": "Nara",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Nara%20Park",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE008",
      "Place_Name": "Todai-ji",
      "Category": "Sightseeing",
      "City": "Nara",
      "Area": "Nara",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Todai-ji",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE009",
      "Place_Name": "Kasuga Taisha",
      "Category": "Sightseeing",
      "City": "Nara",
      "Area": "Nara",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Kasuga%20Taisha",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE010",
      "Place_Name": "Mochiidono Shopping Street",
      "Category": "Shopping",
      "City": "Nara",
      "Area": "Nara",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Mochiidono%20Shopping%20Street",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE011",
      "Place_Name": "Universal Studios Japan",
      "Category": "Theme Park",
      "City": "Osaka",
      "Area": "USJ",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Universal%20Studios%20Japan",
      "Official_URL": "https://www.usj.co.jp/web/en/us/park-guide/schedule/park-hour",
      "Priority": "Must visit"
    },
    {
      "Place_ID": "PLACE012",
      "Place_Name": "Tokyo Station",
      "Category": "Transport Hub",
      "City": "Tokyo",
      "Area": "Yaesu / Marunouchi",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Tokyo%20Station",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE013",
      "Place_Name": "Marunouchi",
      "Category": "Area",
      "City": "Tokyo",
      "Area": "Marunouchi",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Marunouchi%20Tokyo",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE014",
      "Place_Name": "Tokyo Skytree Town",
      "Category": "Sightseeing",
      "City": "Tokyo",
      "Area": "Oshiage",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Tokyo%20Skytree%20Town",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE015",
      "Place_Name": "Senso-ji",
      "Category": "Sightseeing",
      "City": "Tokyo",
      "Area": "Asakusa",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Senso-ji",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE016",
      "Place_Name": "Ueno",
      "Category": "Area",
      "City": "Tokyo",
      "Area": "Ueno",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Ueno%20Tokyo",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE017",
      "Place_Name": "Ameyoko",
      "Category": "Shopping",
      "City": "Tokyo",
      "Area": "Ueno",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Ameyoko",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE018",
      "Place_Name": "Akihabara",
      "Category": "Shopping",
      "City": "Tokyo",
      "Area": "Akihabara",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Akihabara",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE019",
      "Place_Name": "Meiji Jingu",
      "Category": "Sightseeing",
      "City": "Tokyo",
      "Area": "Harajuku",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Meiji%20Jingu",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE020",
      "Place_Name": "Harajuku",
      "Category": "Shopping",
      "City": "Tokyo",
      "Area": "Harajuku",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Harajuku",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE021",
      "Place_Name": "Shibuya",
      "Category": "Area",
      "City": "Tokyo",
      "Area": "Shibuya",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Shibuya",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE022",
      "Place_Name": "Shinjuku",
      "Category": "Area",
      "City": "Tokyo",
      "Area": "Shinjuku",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Shinjuku",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE023",
      "Place_Name": "Nakano Broadway",
      "Category": "Shopping",
      "City": "Tokyo",
      "Area": "Nakano",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Nakano%20Broadway",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE024",
      "Place_Name": "Ikebukuro",
      "Category": "Shopping",
      "City": "Tokyo",
      "Area": "Ikebukuro",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Ikebukuro",
      "Priority": "Optional"
    },
    {
      "Place_ID": "PLACE025",
      "Place_Name": "Narita Airport",
      "Category": "Airport",
      "City": "Chiba",
      "Area": "Narita",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Narita%20International%20Airport",
      "Priority": "Confirmed"
    },
    {
      "Place_ID": "PLACE026",
      "Place_Name": "Namba & Dotonbori",
      "Category": "Food / Area",
      "City": "Osaka",
      "Area": "Namba",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Dotonbori",
      "Priority": "Planned"
    },
    {
      "Place_ID": "PLACE029",
      "Place_Name": "Kansai International Airport",
      "Category": "Airport",
      "City": "Osaka",
      "Area": "KIX",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Kansai%20International%20Airport",
      "Priority": "Confirmed"
    }
  ],
  "food": [],
  "videos": [],
  "bookings": [
    {
      "Booking_ID": "BOOK001",
      "Trip_ID": "TRIP001",
      "Category": "Flight",
      "Item": "DMK → KIX",
      "Related_Type": "Flight",
      "Related_ID": "FLIGHT001",
      "Service_Date": "10/9/2026",
      "Quantity": "2",
      "Currency": "THB",
      "Status": "Confirmed",
      "Cancellation": "Check ticket",
      "Action": "Online check-in and baggage check",
      "Notes": "03:55–11:50",
      "Booking_Ref_Masked": "•••• 7797"
    },
    {
      "Booking_ID": "BOOK002",
      "Trip_ID": "TRIP001",
      "Category": "Hotel",
      "Item": "Tanimachikun Star Hotel Shinfukae 59",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL001",
      "Service_Date": "10/9/2026",
      "Provider": "Trip.com",
      "Quantity": "1",
      "Currency": "THB",
      "Amount": "6869.26",
      "Amount_THB": "6869.26",
      "Status": "Paid",
      "Payment_Due": "Paid",
      "Cancellation": "Free before 8 Oct 23:59 JST",
      "Action": "Send self check-in details",
      "Notes": "4 nights; 2 people",
      "Booking_Ref_Masked": "•••• 4899"
    },
    {
      "Booking_ID": "BOOK003",
      "Trip_ID": "TRIP001",
      "Category": "Activity",
      "Item": "USJ Studio Pass",
      "Related_Type": "Place",
      "Related_ID": "PLACE011",
      "Service_Date": "10/13/2026",
      "Provider": "Klook / selected seller",
      "Quantity": "2",
      "Currency": "THB",
      "Amount": "4174",
      "Amount_THB": "4174",
      "Status": "Not booked",
      "Payment_Due": "46280",
      "Cancellation": "Package terms",
      "Action": "Buy 2 tickets",
      "Notes": "Approx. ฿2,087/person from previous check"
    },
    {
      "Booking_ID": "BOOK004",
      "Trip_ID": "TRIP001",
      "Category": "Activity",
      "Item": "USJ Express Pass",
      "Related_Type": "Place",
      "Related_ID": "PLACE011",
      "Service_Date": "10/13/2026",
      "Provider": "Klook / USJ",
      "Quantity": "2",
      "Currency": "THB",
      "Status": "Not booked",
      "Payment_Due": "46280",
      "Cancellation": "Package terms",
      "Action": "Choose ride set and entry time",
      "Notes": "Verify SUPER NINTENDO WORLD™ entry"
    },
    {
      "Booking_ID": "BOOK005",
      "Trip_ID": "TRIP001",
      "Category": "Pass",
      "Item": "Have Fun in Kansai Pass",
      "Related_Type": "Pass",
      "Service_Date": "10/10/2026",
      "Provider": "Previous offer",
      "Quantity": "1",
      "Currency": "THB",
      "Amount": "923",
      "Amount_THB": "923",
      "Status": "Optional",
      "Cancellation": "Seller terms",
      "Action": "Compare with actual itinerary",
      "Notes": "Previous Buy 1 Get 1 offer; not purchased"
    },
    {
      "Booking_ID": "BOOK006",
      "Trip_ID": "TRIP001",
      "Category": "Bus",
      "Item": "Orion Bus 6112 USJ → Tokyo Yaesu",
      "Related_Type": "Transport",
      "Related_ID": "TRANS005",
      "Service_Date": "10/13/2026",
      "Provider": "Orion Bus",
      "Quantity": "2",
      "Currency": "JPY",
      "Amount": "8000",
      "Amount_THB": "1840",
      "Status": "Needs booking",
      "Payment_Due": "46280",
      "Cancellation": "Operator terms",
      "Action": "Get written confirmation for third bag",
      "Notes": "21:55–06:36; ¥4,000/person",
      "Booking_Ref_Masked": "•••• 6112"
    },
    {
      "Booking_ID": "BOOK007",
      "Trip_ID": "TRIP001",
      "Category": "Luggage",
      "Item": "Big Echo Yaesu Main Store",
      "Related_Type": "Luggage",
      "Related_ID": "LUG001",
      "Service_Date": "10/14/2026",
      "Provider": "ecbo cloak",
      "Quantity": "3",
      "Currency": "JPY",
      "Amount": "2400",
      "Amount_THB": "552",
      "Status": "Needs booking",
      "Payment_Due": "46296",
      "Cancellation": "Provider terms",
      "Action": "Book 3 bags",
      "Notes": "~08:30–15:30; ¥800/bag"
    },
    {
      "Booking_ID": "BOOK008",
      "Trip_ID": "TRIP001",
      "Category": "Hotel",
      "Item": "Noble Park KINSHICHO 201",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL002",
      "Service_Date": "10/14/2026",
      "Provider": "Trip.com",
      "Quantity": "1",
      "Currency": "THB",
      "Amount": "10924.98",
      "Amount_THB": "10924.98",
      "Status": "Paid",
      "Payment_Due": "46293",
      "Cancellation": "Free before 30 Sep",
      "Action": "Verify amenities and final receipt",
      "Notes": "Database uses ฿10,924.98 from latest budget; older booking row showed ฿12,221"
    },
    {
      "Booking_ID": "BOOK009",
      "Trip_ID": "TRIP001",
      "Category": "Option",
      "Item": "Early check-in Tokyo",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL002",
      "Service_Date": "10/14/2026",
      "Provider": "Noble Park KINSHICHO 201",
      "Quantity": "1",
      "Currency": "JPY",
      "Amount": "4500",
      "Amount_THB": "1035",
      "Status": "Optional",
      "Payment_Due": "46309",
      "Cancellation": "Not guaranteed",
      "Action": "Ask after 08:00 on check-in day",
      "Notes": "If available from 12:00; includes luggage storage"
    },
    {
      "Booking_ID": "BOOK010",
      "Trip_ID": "TRIP001",
      "Category": "Flight",
      "Item": "NRT → Bangkok",
      "Related_Type": "Flight",
      "Related_ID": "FLIGHT002",
      "Service_Date": "10/18/2026",
      "Quantity": "2",
      "Currency": "THB",
      "Status": "Confirmed",
      "Cancellation": "Check ticket",
      "Action": "Online check-in and baggage check",
      "Notes": "17:00–21:40",
      "Booking_Ref_Masked": "•••• 7797"
    }
  ],
  "budget": [
    {
      "Expense_ID": "EXP001",
      "Trip_ID": "TRIP001",
      "Category": "ที่พัก",
      "Item": "Osaka hotel 4 คืน",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "THB",
      "Unit_Price": "6869.26",
      "Planned_Amount": "6869.26",
      "Planned_THB": "6869.26",
      "Actual_Amount": "6869.26",
      "Actual_THB": "6869.26",
      "Status": "Paid"
    },
    {
      "Expense_ID": "EXP002",
      "Trip_ID": "TRIP001",
      "Category": "ที่พัก",
      "Item": "Tokyo hotel 4 คืน",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "THB",
      "Unit_Price": "10924.98",
      "Planned_Amount": "10924.98",
      "Planned_THB": "10924.98",
      "Actual_Amount": "10924.98",
      "Actual_THB": "10924.98",
      "Status": "Paid"
    },
    {
      "Expense_ID": "EXP003",
      "Trip_ID": "TRIP001",
      "Category": "กิจกรรม",
      "Item": "USJ Studio Pass",
      "Payer": "Shared",
      "Quantity": "2",
      "Currency": "THB",
      "Unit_Price": "2087",
      "Planned_Amount": "4174",
      "Planned_THB": "4174",
      "Status": "Not booked"
    },
    {
      "Expense_ID": "EXP004",
      "Trip_ID": "TRIP001",
      "Category": "กิจกรรม",
      "Item": "USJ Express Pass",
      "Payer": "Shared",
      "Quantity": "2",
      "Currency": "THB"
    },
    {
      "Expense_ID": "EXP005",
      "Trip_ID": "TRIP001",
      "Category": "พาส",
      "Item": "Have Fun in Kansai Pass",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "THB",
      "Unit_Price": "923",
      "Planned_Amount": "923",
      "Planned_THB": "923",
      "Status": "Optional"
    },
    {
      "Expense_ID": "EXP006",
      "Trip_ID": "TRIP001",
      "Category": "เดินทาง",
      "Item": "Orion Bus 6112",
      "Payer": "Shared",
      "Quantity": "2",
      "Currency": "JPY",
      "Unit_Price": "4000",
      "Planned_Amount": "8000",
      "Planned_THB": "370504000",
      "Status": "Needs booking"
    },
    {
      "Expense_ID": "EXP007",
      "Trip_ID": "TRIP001",
      "Category": "สัมภาระ",
      "Item": "Big Echo Yaesu",
      "Payer": "Shared",
      "Quantity": "3",
      "Currency": "JPY",
      "Unit_Price": "800",
      "Planned_Amount": "2400",
      "Planned_THB": "111151200",
      "Status": "Needs booking"
    },
    {
      "Expense_ID": "EXP008",
      "Trip_ID": "TRIP001",
      "Category": "ที่พัก",
      "Item": "Early check-in Tokyo",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "JPY",
      "Unit_Price": "4500",
      "Planned_Amount": "4500",
      "Planned_THB": "208408500",
      "Status": "Optional"
    },
    {
      "Expense_ID": "EXP009",
      "Trip_ID": "TRIP001",
      "Category": "เดินทาง",
      "Item": "รถไฟ/Metro ภายในญี่ปุ่น",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "JPY",
      "Status": "Estimate needed"
    },
    {
      "Expense_ID": "EXP010",
      "Trip_ID": "TRIP001",
      "Category": "อาหาร",
      "Item": "อาหารและเครื่องดื่ม",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "JPY",
      "Status": "Estimate needed"
    },
    {
      "Expense_ID": "EXP011",
      "Trip_ID": "TRIP001",
      "Category": "กิจกรรม",
      "Item": "Kaiyukan / Osaka Castle / อื่น ๆ",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "JPY",
      "Status": "Estimate needed"
    },
    {
      "Expense_ID": "EXP012",
      "Trip_ID": "TRIP001",
      "Category": "เที่ยวบิน",
      "Item": "ตั๋วเครื่องบินไป-กลับ",
      "Payer": "Shared",
      "Quantity": "1",
      "Currency": "THB",
      "Unit_Price": "35390",
      "Planned_Amount": "35390",
      "Planned_THB": "35390",
      "Actual_Amount": "35390",
      "Actual_THB": "35390",
      "Status": "Paid"
    }
  ],
  "documents": [],
  "contacts": [],
  "tasks": [
    {
      "Task_ID": "TASK001",
      "Trip_ID": "TRIP001",
      "Category": "เอกสาร",
      "Task": "ตรวจพาสปอร์ตและชื่อบนตั๋ว",
      "Due_Date": "9/10/2026",
      "Owner": "เรา",
      "Related_Type": "Document",
      "Related_ID": "DOC001",
      "Status": "To do",
      "Priority": "High",
      "Details": "พาสปอร์ตต้องเหลืออายุใช้งานเพียงพอ"
    },
    {
      "Task_ID": "TASK002",
      "Trip_ID": "TRIP001",
      "Category": "ที่พัก Osaka",
      "Task": "ส่งข้อมูล self check-in",
      "Due_Date": "10/5/2026",
      "Owner": "เรา",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL001",
      "Status": "To do",
      "Priority": "High",
      "Details": "แนบหลักฐานยืนยันตัวตน เวลาเช็กอิน และข้อมูลเที่ยวบิน"
    },
    {
      "Task_ID": "TASK003",
      "Trip_ID": "TRIP001",
      "Category": "ที่พัก Tokyo",
      "Task": "ชำระค่าที่พัก",
      "Due_Date": "9/28/2026",
      "Owner": "เรา",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL002",
      "Status": "To do",
      "Priority": "High",
      "Details": "ยอด ฿12,221"
    },
    {
      "Task_ID": "TASK004",
      "Trip_ID": "TRIP001",
      "Category": "USJ",
      "Task": "ซื้อตั๋ว Studio Pass 2 คน",
      "Due_Date": "9/15/2026",
      "Owner": "เรา",
      "Related_Type": "Place",
      "Related_ID": "PLACE011",
      "Status": "To do",
      "Priority": "High",
      "Details": "วันที่เข้า 13 ต.ค. 2026"
    },
    {
      "Task_ID": "TASK005",
      "Trip_ID": "TRIP001",
      "Category": "USJ",
      "Task": "ตัดสินใจ Express Pass",
      "Due_Date": "9/15/2026",
      "Owner": "เรา",
      "Related_Type": "Place",
      "Related_ID": "PLACE011",
      "Status": "To do",
      "Priority": "High",
      "Details": "ตรวจเวลาเข้า SUPER NINTENDO WORLD™"
    },
    {
      "Task_ID": "TASK006",
      "Trip_ID": "TRIP001",
      "Category": "Night Bus",
      "Task": "ยืนยันรับกระเป๋าใบที่ 3",
      "Due_Date": "9/12/2026",
      "Owner": "เรา",
      "Related_Type": "Transport",
      "Related_ID": "TRANS005",
      "Status": "To do",
      "Priority": "High",
      "Details": "ต้องได้คำตอบเป็นลายลักษณ์อักษรก่อนจอง"
    },
    {
      "Task_ID": "TASK007",
      "Trip_ID": "TRIP001",
      "Category": "Night Bus",
      "Task": "จอง Orion 6112 สำหรับ 2 คน",
      "Due_Date": "9/15/2026",
      "Owner": "เรา",
      "Related_Type": "Transport",
      "Related_ID": "TRANS005",
      "Status": "To do",
      "Priority": "High",
      "Details": "USJ 21:55 → Tokyo Yaesu 06:36"
    },
    {
      "Task_ID": "TASK008",
      "Trip_ID": "TRIP001",
      "Category": "สัมภาระ",
      "Task": "วางแผนส่งกระเป๋า 1 ใบล่วงหน้า",
      "Due_Date": "9/20/2026",
      "Owner": "เรา",
      "Related_Type": "Luggage",
      "Related_ID": "LUG001",
      "Status": "Optional",
      "Priority": "High",
      "Details": "ใช้เมื่อรถบัสไม่ยืนยันรับใบที่ 3; ห้ามส่งตรงโรงแรม Tokyo"
    },
    {
      "Task_ID": "TASK009",
      "Trip_ID": "TRIP001",
      "Category": "ฝากกระเป๋า",
      "Task": "จอง Big Echo Yaesu",
      "Due_Date": "10/1/2026",
      "Owner": "เรา",
      "Related_Type": "Luggage",
      "Related_ID": "LUG001",
      "Status": "To do",
      "Priority": "Medium",
      "Details": "3 ใบ วันที่ 14 ต.ค. ประมาณ 08:30–15:30"
    },
    {
      "Task_ID": "TASK010",
      "Trip_ID": "TRIP001",
      "Category": "ที่พัก Tokyo",
      "Task": "ถาม early check-in",
      "Due_Date": "10/14/2026",
      "Owner": "เรา",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL002",
      "Status": "Optional",
      "Priority": "Low",
      "Details": "ถามหลัง 08:00; หากว่างเริ่ม 12:00 เพิ่ม ¥4,500"
    },
    {
      "Task_ID": "TASK011",
      "Trip_ID": "TRIP001",
      "Category": "การเดินทาง",
      "Task": "เลือกวิธีไป Narita",
      "Due_Date": "10/10/2026",
      "Owner": "เรา",
      "Related_Type": "Transport",
      "Related_ID": "TRANS007",
      "Status": "To do",
      "Priority": "Medium",
      "Details": "คำนึงถึงกระเป๋า 3 ใบและเที่ยวบิน 17:00"
    },
    {
      "Task_ID": "TASK012",
      "Trip_ID": "TRIP001",
      "Category": "การเงิน",
      "Task": "แลกเงิน/ตั้งงบรายวัน",
      "Due_Date": "10/1/2026",
      "Owner": "เรา",
      "Related_Type": "Budget",
      "Status": "To do",
      "Priority": "Medium",
      "Details": "แก้อัตราแลกเปลี่ยนในแท็บงบประมาณ"
    },
    {
      "Task_ID": "TASK013",
      "Trip_ID": "TRIP001",
      "Category": "การสื่อสาร",
      "Task": "เตรียม eSIM/อินเทอร์เน็ต",
      "Due_Date": "10/1/2026",
      "Owner": "เรา",
      "Status": "To do",
      "Priority": "Medium",
      "Details": "ติดตั้งและเก็บ QR/คู่มือออฟไลน์"
    },
    {
      "Task_ID": "TASK014",
      "Trip_ID": "TRIP001",
      "Category": "สัมภาระ",
      "Task": "ชั่งน้ำหนักกระเป๋า",
      "Due_Date": "10/7/2026",
      "Owner": "เรา",
      "Related_Type": "Luggage",
      "Related_ID": "LUG001",
      "Status": "To do",
      "Priority": "Medium",
      "Details": "ตรวจทั้งขาไปและพื้นที่สำหรับของฝาก"
    },
    {
      "Task_ID": "TASK015",
      "Trip_ID": "TRIP001",
      "Category": "สำรองข้อมูล",
      "Task": "บันทึกตั๋ว/ที่อยู่/แผนแบบออฟไลน์",
      "Due_Date": "10/7/2026",
      "Owner": "เรา",
      "Status": "To do",
      "Priority": "Medium",
      "Details": "เก็บสำเนาในมือถือทั้งสองคน"
    },
    {
      "Task_ID": "TASK016",
      "Trip_ID": "TRIP001",
      "Category": "Data quality",
      "Task": "ยืนยันยอดชำระ Noble Park KINSHICHO 201",
      "Owner": "เรา",
      "Related_Type": "Hotel",
      "Related_ID": "HOTEL002",
      "Status": "To do",
      "Priority": "High",
      "Details": "ข้อมูลเดิมมีทั้ง ฿10,924.98 และ ฿12,221 ให้ตรวจยอดล่าสุดจาก Trip.com"
    }
  ],
  "weather": [
    {
      "Weather_ID": "WEATHER001",
      "Trip_ID": "TRIP001",
      "Date": "10/9/2026",
      "City": "Osaka",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER002",
      "Trip_ID": "TRIP001",
      "Date": "10/10/2026",
      "City": "Osaka",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER003",
      "Trip_ID": "TRIP001",
      "Date": "10/11/2026",
      "City": "Kyoto",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER004",
      "Trip_ID": "TRIP001",
      "Date": "10/12/2026",
      "City": "Nara",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER005",
      "Trip_ID": "TRIP001",
      "Date": "10/13/2026",
      "City": "Osaka",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER006",
      "Trip_ID": "TRIP001",
      "Date": "10/14/2026",
      "City": "Tokyo",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER007",
      "Trip_ID": "TRIP001",
      "Date": "10/15/2026",
      "City": "Tokyo",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER008",
      "Trip_ID": "TRIP001",
      "Date": "10/16/2026",
      "City": "Tokyo",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER009",
      "Trip_ID": "TRIP001",
      "Date": "10/17/2026",
      "City": "Tokyo",
      "Forecast_Status": "Not available yet"
    },
    {
      "Weather_ID": "WEATHER010",
      "Trip_ID": "TRIP001",
      "Date": "10/18/2026",
      "City": "Tokyo / Narita",
      "Forecast_Status": "Not available yet"
    }
  ],
  "wishlist": [],
  "emergency": [
    {
      "Emergency_ID": "EMERG001",
      "Category": "Police",
      "Name": "Japan Police",
      "Phone": "110",
      "Availability": "24 hours",
      "Action": "Call for urgent police assistance",
      "Source_URL": "https://www.japan.travel/en/plan/hotline/",
      "Offline_Ready": "TRUE",
      "Notes": "Free emergency number"
    },
    {
      "Emergency_ID": "EMERG002",
      "Category": "Fire / Ambulance",
      "Name": "Fire and Ambulance",
      "Phone": "119",
      "Availability": "24 hours",
      "Action": "Call for fire or medical emergency",
      "Source_URL": "https://www.japan.travel/en/plan/hotline/",
      "Offline_Ready": "TRUE",
      "Notes": "Free emergency number"
    },
    {
      "Emergency_ID": "EMERG003",
      "Category": "Tourist support",
      "Name": "JNTO Japan Visitor Hotline",
      "Phone": "+81 50-3816-2787",
      "Availability": "24 hours",
      "Action": "Call for accidents, illness or disasters",
      "Source_URL": "https://www.japan.travel/en/plan/hotline/",
      "Offline_Ready": "TRUE",
      "Notes": "English, Chinese and Korean support"
    },
    {
      "Emergency_ID": "EMERG004",
      "Category": "Embassy",
      "Name": "Royal Thai Embassy, Tokyo",
      "Phone": "+81 3-5789-2433",
      "Availability": "Office hours; verify emergency line",
      "Action": "Contact for passport loss or consular assistance",
      "Address": "3-14-6 Kami-Osaki, Shinagawa-ku, Tokyo 141-0021",
      "Google_Maps_URL": "https://www.google.com/maps/search/?api=1&query=Royal%20Thai%20Embassy%20Tokyo",
      "Source_URL": "https://site.thaiembassy.jp/",
      "Offline_Ready": "TRUE",
      "Notes": "Verify after-hours emergency channel before departure"
    },
    {
      "Emergency_ID": "EMERG005",
      "Category": "Passport loss",
      "Name": "Lost passport procedure",
      "Action": "Report to police, obtain police report, contact Thai Embassy and prepare identity evidence",
      "Source_URL": "https://site.thaiembassy.jp/",
      "Offline_Ready": "TRUE",
      "Notes": "Keep passport copies offline on both phones"
    },
    {
      "Emergency_ID": "EMERG006",
      "Category": "Insurance",
      "Name": "Travel insurance contact",
      "Availability": "24 hours",
      "Action": "Fill insurer, policy number and assistance phone before departure",
      "Offline_Ready": "FALSE",
      "Notes": "Do not store unnecessary sensitive details in frontend"
    }
  ]
};
